server:
  port: 80
spring:
  datasource:

    url: jdbc:mysql://3.83.146.138:3306/rental?characterEncoding=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: true
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  resources:
    static-locations: ["classpath:/META-INF/resources/","classpath:/resources/","classpath:/static/","classpath:/static/upload","classpath:/public/","classpath:/templates/","file:${web.upload-path}","file:/static/"]


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.**.entity
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    capital-mode: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level.com.rental.mapper: debug


